# .prettierrc.yaml
proseWrap: 'preserve'
trailingComma: 'es5'
tabWidth: 4
semi: true
singleQuote: true
quoteProps: 'preserve'
printWidth: 120
overrides:
  - files:
      - '*.json'
      - '*.yml'
    options:
      tabWidth: 2
  - files:
      - '*.ts'
      - '*.tsx'
    options:
      parser: 'typescript'
